In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("census.csv")
print(data.shape)
data.head()

(48842, 15)


age         workclass    fnlwgt  education  education_num  \
0   39         State-gov   77516.0  Bachelors             13   
1   50  Self-emp-not-inc   83311.0  Bachelors             13   
2   38           Private  215646.0    HS-grad              9   
3   53           Private  234721.0       11th              7   
4   28           Private  338409.0  Bachelors             13   

       marital_status         occupation   relationship   race     sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male   
1  Married-civ-spouse    Exec-managerial        Husband  White    Male   
2            Divorced  Handlers-cleaners  Not-in-family  White    Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female   

   capital_gain  capital_loss  hours_per_week native_country income_level  
0        2174.0           0.0            40.0  United-States        <=50K  
1           0.0           0.0            13.0  United-States        <=50K  
2           0.0           0.0            40.0  United-States        <=50K  
3           0.0           0.0            40.0  United-States        <=50K  
4           0.0           0.0            40.0           Cuba        <=50K

In [3]:
data["income_level"]= data["income_level"].str.replace("=", "") 
data["income_level"]

0        <50K
1        <50K
2        <50K
3        <50K
4        <50K
         ... 
48837    <50K
48838    <50K
48839    <50K
48840    <50K
48841    >50K
Name: income_level, Length: 48842, dtype: object

In [4]:
data=data.drop("fnlwgt",axis=1)
data

age         workclass  education  education_num      marital_status  \
0       39         State-gov  Bachelors             13       Never-married   
1       50  Self-emp-not-inc  Bachelors             13  Married-civ-spouse   
2       38           Private    HS-grad              9            Divorced   
3       53           Private       11th              7  Married-civ-spouse   
4       28           Private  Bachelors             13  Married-civ-spouse   
...    ...               ...        ...            ...                 ...   
48837   39           Private  Bachelors             13            Divorced   
48838   64                 ?    HS-grad              9             Widowed   
48839   38           Private  Bachelors             13  Married-civ-spouse   
48840   44           Private  Bachelors             13            Divorced   
48841   35      Self-emp-inc  Bachelors             13  Married-civ-spouse   

              occupation    relationship                race     sex  \
0           Adm-clerical   Not-in-family               White    Male   
1        Exec-managerial         Husband               White    Male   
2      Handlers-cleaners   Not-in-family               White    Male   
3      Handlers-cleaners         Husband               Black    Male   
4         Prof-specialty            Wife               Black  Female   
...                  ...             ...                 ...     ...   
48837     Prof-specialty   Not-in-family               White  Female   
48838                  ?  Other-relative               Black    Male   
48839     Prof-specialty         Husband               White    Male   
48840       Adm-clerical       Own-child  Asian-Pac-Islander    Male   
48841    Exec-managerial         Husband               White    Male   

       capital_gain  capital_loss  hours_per_week native_country income_level  
0            2174.0           0.0            40.0  United-States         <50K  
1               0.0           0.0            13.0  United-States         <50K  
2               0.0           0.0            40.0  United-States         <50K  
3               0.0           0.0            40.0  United-States         <50K  
4               0.0           0.0            40.0           Cuba         <50K  
...             ...           ...             ...            ...          ...  
48837           0.0           0.0            36.0  United-States         <50K  
48838           0.0           0.0            40.0  United-States         <50K  
48839           0.0           0.0            50.0  United-States         <50K  
48840        5455.0           0.0            40.0  United-States         <50K  
48841           0.0           0.0            60.0  United-States         >50K  

[48842 rows x 14 columns]

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   age             48842 non-null  int64  
 1   workclass       48842 non-null  object 
 2   education       48842 non-null  object 
 3   education_num   48842 non-null  int64  
 4   marital_status  48842 non-null  object 
 5   occupation      48842 non-null  object 
 6   relationship    48842 non-null  object 
 7   race            48842 non-null  object 
 8   sex             48842 non-null  object 
 9   capital_gain    48842 non-null  float64
 10  capital_loss    48842 non-null  float64
 11  hours_per_week  48842 non-null  float64
 12  native_country  48842 non-null  object 
 13  income_level    48842 non-null  object 
dtypes: float64(3), int64(2), object(9)
memory usage: 5.2+ MB


In [6]:
(data =="?").any()

age               False
workclass          True
education         False
education_num     False
marital_status    False
occupation         True
relationship      False
race              False
sex               False
capital_gain      False
capital_loss      False
hours_per_week    False
native_country     True
income_level      False
dtype: bool

In [7]:
list=data.select_dtypes(include=object).columns.tolist()
for col in list:
    data.loc[data[col]=="?", col] = np.nan

data

age         workclass  education  education_num      marital_status  \
0       39         State-gov  Bachelors             13       Never-married   
1       50  Self-emp-not-inc  Bachelors             13  Married-civ-spouse   
2       38           Private    HS-grad              9            Divorced   
3       53           Private       11th              7  Married-civ-spouse   
4       28           Private  Bachelors             13  Married-civ-spouse   
...    ...               ...        ...            ...                 ...   
48837   39           Private  Bachelors             13            Divorced   
48838   64               NaN    HS-grad              9             Widowed   
48839   38           Private  Bachelors             13  Married-civ-spouse   
48840   44           Private  Bachelors             13            Divorced   
48841   35      Self-emp-inc  Bachelors             13  Married-civ-spouse   

              occupation    relationship                race     sex  \
0           Adm-clerical   Not-in-family               White    Male   
1        Exec-managerial         Husband               White    Male   
2      Handlers-cleaners   Not-in-family               White    Male   
3      Handlers-cleaners         Husband               Black    Male   
4         Prof-specialty            Wife               Black  Female   
...                  ...             ...                 ...     ...   
48837     Prof-specialty   Not-in-family               White  Female   
48838                NaN  Other-relative               Black    Male   
48839     Prof-specialty         Husband               White    Male   
48840       Adm-clerical       Own-child  Asian-Pac-Islander    Male   
48841    Exec-managerial         Husband               White    Male   

       capital_gain  capital_loss  hours_per_week native_country income_level  
0            2174.0           0.0            40.0  United-States         <50K  
1               0.0           0.0            13.0  United-States         <50K  
2               0.0           0.0            40.0  United-States         <50K  
3               0.0           0.0            40.0  United-States         <50K  
4               0.0           0.0            40.0           Cuba         <50K  
...             ...           ...             ...            ...          ...  
48837           0.0           0.0            36.0  United-States         <50K  
48838           0.0           0.0            40.0  United-States         <50K  
48839           0.0           0.0            50.0  United-States         <50K  
48840        5455.0           0.0            40.0  United-States         <50K  
48841           0.0           0.0            60.0  United-States         >50K  

[48842 rows x 14 columns]

In [8]:
data.isna().sum() 

age                  0
workclass         2799
education            0
education_num        0
marital_status       0
occupation        2809
relationship         0
race                 0
sex                  0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country     857
income_level         0
dtype: int64

In [9]:
def CountFrequency(my_list): 
  
    # Creating an empty dictionary  
    freq = {} 
    for item in my_list: 
        if (item in freq): 
            freq[item] += 1
        else: 
            freq[item] = 1
  
    for key, value in freq.items(): 
        print ("%s : % d"%(key, value)) 

In [10]:
CountFrequency(data.native_country) 

United-States :  43832
Cuba :  138
Jamaica :  106
India :  151
nan :  857
Mexico :  951
South :  115
Puerto-Rico :  184
Honduras :  20
England :  127
Canada :  182
Germany :  206
Iran :  59
Philippines :  295
Italy :  105
Poland :  87
Columbia :  85
Cambodia :  28
Thailand :  30
Ecuador :  45
Laos :  23
Taiwan :  65
Haiti :  75
Portugal :  67
Dominican-Republic :  103
El-Salvador :  155
France :  38
Guatemala :  88
China :  122
Japan :  92
Yugoslavia :  23
Peru :  46
Outlying-US(Guam-USVI-etc) :  23
Scotland :  21
Trinadad&Tobago :  27
Greece :  49
Nicaragua :  49
Vietnam :  86
Hong :  30
Ireland :  37
Hungary :  19
Holand-Netherlands :  1


In [11]:
data['native_country'] = data['native_country'].fillna('United-States')
data.native_country.isna().sum() 

0

In [12]:
data=data.dropna()
data.shape

(46033, 14)

In [13]:
categorical_cols = ['native_country','workclass', 'education', 'marital_status', 'occupation','relationship','race','sex','income_level'] 
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data[categorical_cols] =data[categorical_cols].apply(lambda col: le.fit_transform(col))
categorical_cols=pd.DataFrame(data[categorical_cols])
categorical_cols

c:\users\admin\appdata\local\programs\python\python37\lib\site-packages\pandas\core\frame.py:3065: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]


native_country  workclass  education  marital_status  occupation  \
0                  38          5          9               4           0   
1                  38          4          9               2           3   
2                  38          2         11               0           5   
3                  38          2          1               2           5   
4                   4          2          9               2           9   
...               ...        ...        ...             ...         ...   
48836              38          2          9               4           9   
48837              38          2          9               0           9   
48839              38          2          9               2           9   
48840              38          2          9               0           0   
48841              38          3          9               2           3   

       relationship  race  sex  income_level  
0                 1     4    1             0  
1                 0     4    1             0  
2                 1     4    1             0  
3                 0     2    1             0  
4                 5     2    0             0  
...             ...   ...  ...           ...  
48836             3     4    1             0  
48837             1     4    0             0  
48839             0     4    1             0  
48840             3     1    1             0  
48841             0     4    1             1  

[46033 rows x 9 columns]

In [14]:
data=data.drop(['native_country','workclass', 'education', 'marital_status', 'occupation','relationship','race','sex','income_level'],axis=1)
data


age  education_num  capital_gain  capital_loss  hours_per_week
0       39             13        2174.0           0.0            40.0
1       50             13           0.0           0.0            13.0
2       38              9           0.0           0.0            40.0
3       53              7           0.0           0.0            40.0
4       28             13           0.0           0.0            40.0
...    ...            ...           ...           ...             ...
48836   33             13           0.0           0.0            40.0
48837   39             13           0.0           0.0            36.0
48839   38             13           0.0           0.0            50.0
48840   44             13        5455.0           0.0            40.0
48841   35             13           0.0           0.0            60.0

[46033 rows x 5 columns]

In [15]:
df_model=pd.concat([data,categorical_cols],axis=1)
df_model

age  education_num  capital_gain  capital_loss  hours_per_week  \
0       39             13        2174.0           0.0            40.0   
1       50             13           0.0           0.0            13.0   
2       38              9           0.0           0.0            40.0   
3       53              7           0.0           0.0            40.0   
4       28             13           0.0           0.0            40.0   
...    ...            ...           ...           ...             ...   
48836   33             13           0.0           0.0            40.0   
48837   39             13           0.0           0.0            36.0   
48839   38             13           0.0           0.0            50.0   
48840   44             13        5455.0           0.0            40.0   
48841   35             13           0.0           0.0            60.0   

       native_country  workclass  education  marital_status  occupation  \
0                  38          5          9               4           0   
1                  38          4          9               2           3   
2                  38          2         11               0           5   
3                  38          2          1               2           5   
4                   4          2          9               2           9   
...               ...        ...        ...             ...         ...   
48836              38          2          9               4           9   
48837              38          2          9               0           9   
48839              38          2          9               2           9   
48840              38          2          9               0           0   
48841              38          3          9               2           3   

       relationship  race  sex  income_level  
0                 1     4    1             0  
1                 0     4    1             0  
2                 1     4    1             0  
3                 0     2    1             0  
4                 5     2    0             0  
...             ...   ...  ...           ...  
48836             3     4    1             0  
48837             1     4    0             0  
48839             0     4    1             0  
48840             3     1    1             0  
48841             0     4    1             1  

[46033 rows x 14 columns]

In [17]:
X = df_model.drop(['income_level'], axis=1)
X_col = X.columns

In [22]:
#The StandardScaler assumes your data is normally distributed within each feature and will scale them such
#that the distribution is now centred around 0, with a standard deviation of 1

In [18]:
y = df_model['income_level']
from sklearn.preprocessing import StandardScaler
X = StandardScaler().fit_transform(X.values)
from sklearn.model_selection import train_test_split

In [26]:
standard_scalar = pd.DataFrame(X, columns=X_col)
standard_scalar.head()

age  education_num  capital_gain  capital_loss  hours_per_week  \
0  0.033580       1.119747      0.139623     -0.218916       -0.078962   
1  0.866653       1.119747     -0.146826     -0.218916       -2.326913   
2 -0.042154      -0.440294     -0.146826     -0.218916       -0.078962   
3  1.093855      -1.220314     -0.146826     -0.218916       -0.078962   
4 -0.799493       1.119747     -0.146826     -0.218916       -0.078962   

   native_country  workclass  education  marital_status  occupation  \
0        0.260513   2.917802  -0.343334        0.942739   -1.486080   
1        0.260513   1.873791  -0.343334       -0.392392   -0.740440   
2        0.260513  -0.214232   0.181138       -1.727524   -0.243347   
3        0.260513  -0.214232  -2.441220       -0.392392   -0.243347   
4       -5.378274  -0.214232  -0.343334       -0.392392    0.750839   

   relationship      race       sex  
0     -0.257918  0.389597  0.692456  
1     -0.883984  0.389597  0.692456  
2     -0.257918  0.389597  0.692456  
3     -0.883984 -1.986439  0.692456  
4      2.246347 -1.986439 -1.444136

### Implementing KNN with standard scaling

In [27]:
X_train, X_test, y_train, y_test = train_test_split(standard_scalar, y, train_size=0.8,random_state=42)

In [32]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5,
                           p=2, metric='minkowski')
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [29]:
from sklearn import preprocessing
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import confusion_matrix, roc_auc_score
def print_score(clf, X_train, X_test, y_train, y_test, train=True):
    '''
    v0.1 Follow the scikit learn library format in terms of input
    print the accuracy score, classification report and confusion matrix of classifier
    '''
    lb = preprocessing.LabelBinarizer()
    lb.fit(y_train)
    if train:
        '''
        training performance
        '''
        res = clf.predict(X_train)
        print("Train Result:\n")
        print("accuracy score: {0:.4f}\n".format(accuracy_score(y_train, 
                                                                res)))
        print("Classification Report: \n {}\n".format(classification_report(y_train, 
                                                                            res)))
        print("Confusion Matrix: \n {}\n".format(confusion_matrix(y_train, 
                                                                  res)))
        print("ROC AUC: {0:.4f}\n".format(roc_auc_score(lb.transform(y_train), 
                                                      lb.transform(res))))

        res = cross_val_score(clf, X_train, y_train, cv=10, scoring='accuracy')
        print("Average Accuracy: \t {0:.4f}".format(np.mean(res)))
        print("Accuracy SD: \t\t {0:.4f}".format(np.std(res)))
        
    elif train==False:
        '''
        test performance
        '''
        res_test = clf.predict(X_test)
        print("Test Result:\n")        
        print("accuracy score: {0:.4f}\n".format(accuracy_score(y_test, 
                                                                res_test)))
        print("Classification Report: \n {}\n".format(classification_report(y_test, 
                                                                            res_test)))
        print("Confusion Matrix: \n {}\n".format(confusion_matrix(y_test, 
                                                                  res_test)))   
        print("ROC AUC: {0:.4f}\n".format(roc_auc_score(lb.transform(y_test), 
                                                      lb.transform(res_test))))

### Implementing KNN with min max scaling

In [31]:
print_score(knn, X_train, X_test, y_train, y_test, train=True)
print_score(knn, X_train, X_test, y_train, y_test, train=False)

Train Result:

accuracy score: 0.8761

Classification Report: 
               precision    recall  f1-score   support

           0       0.90      0.94      0.92     27678
           1       0.78      0.69      0.74      9148

    accuracy                           0.88     36826
   macro avg       0.84      0.82      0.83     36826
weighted avg       0.87      0.88      0.87     36826


Confusion Matrix: 
 [[25909  1769]
 [ 2794  6354]]

ROC AUC: 0.8153

Average Accuracy: 	 0.8251
Accuracy SD: 		 0.0034
Test Result:

accuracy score: 0.8313

Classification Report: 
               precision    recall  f1-score   support

           0       0.88      0.90      0.89      6933
           1       0.67      0.62      0.64      2274

    accuracy                           0.83      9207
   macro avg       0.78      0.76      0.77      9207
weighted avg       0.83      0.83      0.83      9207


Confusion Matrix: 
 [[6251  682]
 [ 871 1403]]

ROC AUC: 0.7593



In [25]:
#Also known as min-max scaling or min-max normalization, is the simplest method and consists in rescaling 
#the range of features to scale the range in [0, 1] or [−1, 1]. Selecting the target range depends on 
#the nature of the data.
from sklearn.preprocessing import MinMaxScaler
min_max_scalar=pd.DataFrame(MinMaxScaler().fit_transform(df_model.drop(['income_level'], axis=1).values), columns=X_col)
min_max_scalar.head()

age  education_num  capital_gain  capital_loss  hours_per_week  \
0  0.301370       0.800000       0.02174           0.0        0.397959   
1  0.452055       0.800000       0.00000           0.0        0.122449   
2  0.287671       0.533333       0.00000           0.0        0.397959   
3  0.493151       0.400000       0.00000           0.0        0.397959   
4  0.150685       0.800000       0.00000           0.0        0.397959   

   native_country  workclass  education  marital_status  occupation  \
0            0.95   0.833333   0.600000        0.666667    0.000000   
1            0.95   0.666667   0.600000        0.333333    0.230769   
2            0.95   0.333333   0.733333        0.000000    0.384615   
3            0.95   0.333333   0.066667        0.333333    0.384615   
4            0.10   0.333333   0.600000        0.333333    0.692308   

   relationship  race  sex  
0           0.2   1.0  1.0  
1           0.0   1.0  1.0  
2           0.2   1.0  1.0  
3           0.0   0.5  1.0  
4           1.0   0.5  0.0

In [35]:
X_train, X_test, y_train, y_test = train_test_split(min_max_scalar, y, train_size=0.8,random_state=42)

In [36]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5,
                           p=2, metric='minkowski')
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [37]:
print_score(knn, X_train, X_test, y_train, y_test, train=True)
print_score(knn, X_train, X_test, y_train, y_test, train=False)

Train Result:

accuracy score: 0.8717

Classification Report: 
               precision    recall  f1-score   support

           0       0.90      0.93      0.92     27678
           1       0.78      0.68      0.73      9148

    accuracy                           0.87     36826
   macro avg       0.84      0.81      0.82     36826
weighted avg       0.87      0.87      0.87     36826


Confusion Matrix: 
 [[25870  1808]
 [ 2915  6233]]

ROC AUC: 0.8080

Average Accuracy: 	 0.8197
Accuracy SD: 		 0.0040
Test Result:

accuracy score: 0.8257

Classification Report: 
               precision    recall  f1-score   support

           0       0.87      0.90      0.89      6933
           1       0.67      0.59      0.63      2274

    accuracy                           0.83      9207
   macro avg       0.77      0.75      0.76      9207
weighted avg       0.82      0.83      0.82      9207


Confusion Matrix: 
 [[6264  669]
 [ 936 1338]]

ROC AUC: 0.7459



### Implementing SVM

In [44]:
X_train, X_test, y_train, y_test = train_test_split(standard_scalar, y, train_size=0.8,random_state=42)

In [45]:
from sklearn.svm import SVC
classifier = SVC(kernel='rbf', random_state = 42)
classifier.fit(X_train,y_train)

SVC(random_state=42)

In [46]:
y_pred = classifier.predict(X_test)

In [47]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[6500,  433],
       [ 994, 1280]], dtype=int64)

In [48]:
print_score(classifier, X_train, X_test, y_train, y_test, train=True)
print_score(classifier, X_train, X_test, y_train, y_test, train=False)

Train Result:

accuracy score: 0.8519

Classification Report: 
               precision    recall  f1-score   support

           0       0.87      0.94      0.91     27678
           1       0.77      0.57      0.66      9148

    accuracy                           0.85     36826
   macro avg       0.82      0.76      0.78     36826
weighted avg       0.85      0.85      0.84     36826


Confusion Matrix: 
 [[26144  1534]
 [ 3921  5227]]

ROC AUC: 0.7580

Average Accuracy: 	 0.8457
Accuracy SD: 		 0.0055
Test Result:

accuracy score: 0.8450

Classification Report: 
               precision    recall  f1-score   support

           0       0.87      0.94      0.90      6933
           1       0.75      0.56      0.64      2274

    accuracy                           0.85      9207
   macro avg       0.81      0.75      0.77      9207
weighted avg       0.84      0.85      0.84      9207


Confusion Matrix: 
 [[6500  433]
 [ 994 1280]]

ROC AUC: 0.7502

